config/routes.rb
Massagemyway::Application.routes.draw do
  
  resources :bookings, :only => [:new, :create]
  match 'about' => 'pages#about', :as => :about
  match 'services' => 'pages#services', :as => :services
  match 'booking' => 'pages#booking', :as => :booking
  match 'therapists' => 'pages#therapists', :as => :therapists
  match 'contact' => 'pages#contact', :as => :contact
  match 'policies' => 'pages#policies', :as => :policies
  root :to => "pages#index"

end

app/models/booking.rb
class Booking
  include ActiveModel::Validations

  validates_presence_of :name, :email, :phone
  # to deal with form, you must have an id attribute
  attr_accessor :id, :name, :email, :phone, :therapist, :details

  def initialize(attributes = {})
    attributes.each do |key, value|
      self.send("#{key}=", value)
    end
    @attributes = attributes
  end

  def read_attribute_for_validation(key)
    @attributes[key]
  end

  def to_key; end

  def save
    if self.valid?
      Notifier.booking_notification(self).deliver
      return true
    end
    return false
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  layout :set_layout
  def set_layout
    request.xhr? ? 'window' : 'application'
  end
  
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  inherit_resources
  respond_to :js

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<p class="small">
Once you submit your request, we get to work right away to find the best therapist to match your preferences. 
Please note, it can take up to an hour to get back to you based on the kind of therapist you need and what is available.
</p>
<div class="under"></div>
<p>
<%= simple_form_for @booking, :url => bookings_path, :remote => true do |f| %>
  <%= f.input :name %>
  <%= f.input :email %>
  <%= f.input :phone %>
  <%= f.input :therapist, :collection => ["Male", "Female", "No Preference"], :as => :radio %>
  <%= f.input :details, :as => :text, :hint => "Describe the type of massage you're looking for, and/or the reason you need a massage (stiffness, soreness, injury, ect.)" %>
  <%= f.submit "Send" %>
<% end %>
</p>
<div class="under"></div>

app/views/bookings/_thanks.html.erb
<p>Thank you for booking with Massage My Way.</p>

app/views/bookings/new.html.erb
<h2>Book Online</h2>
<section>
<%= render 'form' %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Massage My Way: LA's Premier Mobile Massage</title>
    <%= stylesheet_link_tag 'screen' %>
    <%= javascript_include_tag :defaults, "jquery.tools.js" %>
    <%= csrf_meta_tag %>


<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-23500847-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

  </head>
  <body>
    <div id="body">
      <div id="page">
        <div id="header">
          <a href="/" id="logo">
          <h1>Massage My Way</h1>
          </a>
          <div class="wrapper">
            <span class="left">
              <strong>Massage My Way</strong> - LA's Premier Mobile Massage
            </span>
            <span class="right">
              <a href="/bookings/new" rel="modal"><strong>Book Online</strong></a> or
              <strong>Call: (310) 853-1830</strong>
            </span>
          </div>
          <div id="nav" class="clearfix">
            <%= render_navigation %>
          </div>
        </div>
        
        <div class="main">
          <div id="content">

            <div class="box_top_left">
              <div class="box_top_right">
                <div class="box_top">
                </div>
              </div>
            </div>
            <div class="box_left">
              <div class="box_right">
                <div class="box">
                  <div class="pad">
                    <%= yield %>
                  </div>
                </div>
              </div>
              <div class="box_bot_left">
                <div class="box_bot_right">
                  <div class="box_bot">
                  </div>
                </div>
              </div>
          </section>
        </div>
        <div id="footer" class="clearfix">
          <span class="left">
            &copy; 2010
            <strong>Massage My Way</strong> &nbsp;|&nbsp;
            <%= link_to "Our Policies", policies_path %>
          </span>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application_old.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Massage My Way: LA's Premier Mobile Massage</title>
    <%= stylesheet_link_tag :all %>
    <%= javascript_include_tag :defaults, "jquery.tools.js" %>
    <!--[if lt IE 9]>
    <script type="text/javascript" src="/javascripts/html5.js"></script>
    <![endif]-->
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div class="body <%= params[:action] %>">
      <div class="main">
        <!--header -->
        <header>
          <a href="/" id="logo">
          <h1>Massage My Way</h1>
          </a>
          <div class="wrapper">
            <span class="left">
              <strong>Massage My Way</strong> - LA's Premier Mobile Massage
            </span>
            <span class="right">
              <a href="/bookings/new" rel="modal"><strong>Book Online</strong></a> or
              <strong>Call: (310) 309-7814</strong>
            </span>
          </div>
          <nav>
            <%= render_navigation %>
          </nav>
          <div class="banner">
            <%= image_tag "header_#{params[:action]}.jpg" %>
          </div>
        </header>
      </div>
    </div>
    <div class="main">
      <!--header end-->
      <!--content -->
      <section id="content">
        <div class="box_top_left">
          <div class="box_top_right">
            <div class="box_top">
            </div>
          </div>
        </div>
        <div class="box_left">
          <div class="box_right">
            <div class="box">
              <div class="pad">
                <%= yield %>
              </div>
            </div>
          </div>
          <div class="box_bot_left">
            <div class="box_bot_right">
              <div class="box_bot">
              </div>
            </div>
          </div>
      </section>
      <!--content end-->
      <!--footer -->
      <footer>
        <div class="wrapper">
          <span class="left">
            &nbsp;&copy; 2010
            <strong>Massage My Way</strong><!-- &nbsp;|&nbsp;
            <a href="/policy/">Our Policies</a>-->
          </span>
<!--
          <ul id="icons">
            <li>
              <a href="#">
              <img src="/images/icon1.jpg" alt="">
              </a>
            </li>
            <li>
              <a href="#">
              <img src="/images/icon2.jpg" alt="">
              </a>
            </li>
            <li>
              <a href="#">
              <img src="/images/icon3.jpg" alt="">
              </a>
            </li>
            <li>
              <a href="#">
              <img src="/images/icon4.jpg" alt="">
              </a>
            </li>
          </ul>
-->
          <span class="right">
            <!-- {%FOOTER_LINK} -->
          </span>
        </div>
      </footer>
      <!--footer end-->   
    </div>
  </body>
</html>

app/views/layouts/window.html.erb
<%= yield %>

app/views/notifier/booking_notification.html.erb
Booking Form
---------------------------------
Name:       <%= @booking.name %>
Email:      <%= @booking.email %>
Phone:      <%= @booking.phone %>
Therapist:  <%= @booking.therapist %>
---------------------------------
<%= @booking.details %>

app/views/pages/_book.html.erb
<div class="promo pad-top clearfix">
  <%= link_to "Book Online Now", new_booking_path, :class => "button", :rel =>"modal" %>
</div>

app/views/pages/about.html.erb
<div class="wrapper pad_bot1">
  <h2>Our Vision</h2>
  <div class="wrapper pad_bot1">
    <div class="figure left marg_right1 border">
      <span class="photo">
        <img src="/images/photos/shiatsu.jpg" alt="">
        <span class="overlay overlay-large"></span>
      </span>
    </div>
    <h4>Massage My Way</h4>
    <p>
      was created to give people access to on site and on demand massage therapy keeping in mind these key elements -  providing the highest quality massage and keeping it affordable. We know that when you want a massage it has to be detailed, knowledgeable, effective, and attentive to your needs.
    </p>
    <p>
      We only employ the best and brightest therapists in the trade. We also provide on going training to make sure they stay at the top of the field. You can rest assured you will receive the highest quality of care.
    </p>
  </div>
</div>
<div class="under">
</div>
<div class="wrapper pad_bot1">
  <h2>what we offer</h2>
  <div class="wrapper pad_bot1">
    <ul class="list1 col1">
      <li>
        <a href="#">Swedish Massage</a>
      </li>
      <li>
        <a href="#">Deep Tissue</a>
      </li>
      <li>
        <a href="#">Shiats</a>u
      </li>
      <li>
        <a href="#">Sports Massage</a>
      </li>
    </ul>
    <ul class="list1 col1 pad_left1">
      <li>
        <a href="#">Reflexology</a>
      </li>
      <li>
        <a href="#">Craniosacral Therapy</a>
      </li>
      <li>
        <a href="#">Dry Body Scrub</a>
      </li>
      <li>
        <a href="#">Thai Massage</a>
      </li>
    </ul>
    <ul class="list1 col1 pad_left1">
      <li>
        <a href="#">Couples Massage</a>
      </li>
      <li>
        <a href="#">Lymphatic Massage</a>
      </li>
      <li>
        <a href="#">Chair Massage</a>
      </li>
      <li>
        <a href="#">Combo Massage</a>
      </li>
    </ul>
  </div>
  <a href="/services/" class="link1">View all Services</a>
</div>
<div class="under">
</div>
<div class="wrapper pad_bot1">
  <h2>Service Areas</h2>
  <p>
    We currently serve the westside in the following areas:
    <strong>West Hollywood</strong>,
    <strong>Beverly Hills</strong>,
    <strong>Santa Monica</strong>,
    <strong>Westwood</strong>,
    <strong>West LA</strong>,
    <strong>Brentwood</strong>,
    <strong>Venice</strong>,
    <strong>Marina Del-Rey</strong>,
    <strong>Playa Del Rey</strong>, and
    <strong>Manhattan Beach</strong>.
  </p>
  <a href="/booking/" class="link1">Booking With Us</a>
</div>

app/views/pages/booking.html.erb
<div class="layout half clearfix">
  <div class="col first">

    <div class="figure border">
      <span class="photo">
        <%= image_tag "photos/booking1.jpg" %>
        <span class="overlay">
        </span>
    </div>
    <h2>Packages &amp; Pricing</h2>
    <p>
      To receive the benefits of our low price offerings choose from one of the following package deals
    </p>
    <p>
      60 min. massage $95
      <br>
      Package of 3 one hour massages $255
      <small>
        (a savings of $10 per massage)
      </small>
      <br>
      Package of 6 one hour massages $450
      <small>
        (a savings of $20 per massage)
      </small>
      <br>
    </p>
    <p>
      90 min. massage $140
      <br>
      Package of 3 90min. massages $375
      <small>
        (a savings of $15 per massage)
      </small>
      <br>
      Package of 6 90min. massages $660
      <small>
        (a savings of $30 per massage)
      </small>
      <br>
    </p>
    <p>
      In addition to personalized massage sessions, we offer event and chair massage. Call to inquire.
    </p>
  </div>
  <div class="col second">
    <h3>To Help You On Your Healing Path</h3>
    <div class="promo">
      <p>
        First time client discount
        <br>
        You pay only $77 for a one hour massage
      </p>
      <%= link_to "Book Online Now", new_booking_path, :class => "button", :rel =>"modal" %>
    </div>
    <br><br><br><br><br><br><br><br>
    <div class="figure border">
      <span class="photo">
        <%= image_tag "photos/booking2.jpg" %>
        <span class="overlay">
        </span>
    </div>
  </div>
</div>
<%= render "book" %>

app/views/pages/contact.html.erb
<div class="figure clearfix"><%= image_tag "photos/composition.jpg" %></div>
<div class="layout fourths clearfix pad-top">
  <div class="first">
    <div class="figure"><%= image_tag "photos/contact1.jpg" %></div>
  </div>
  <div class="second">
    <!--<p><strong>We are ready to take your massage request.</strong></p>-->
    <h3>Massage My Way</h3>
    <p>
    Phone: (310) 853-1830
    <br>
    Email: <a rel="modal" href="/bookings/new">Contact Us</a>
    <p>
      In addition to personalized massage sessions, we offer event and chair massage. Call to inquire.
    </p>
    <p>
      We currently serve the Los Angeles westside in the following areas:
    </p>
    <p>
      <strong>West Hollywood</strong>,
      <strong>Beverly Hills</strong>,
      <strong>Santa Monica</strong>,
      <strong>Westwood</strong>,
      <strong>West LA</strong>,
      <strong>Brentwood</strong>,
      <strong>Venice</strong>,
      <strong>Marina Del-Rey</strong>,
      <strong>Playa Del Rey</strong>, and
      <strong>Manhattan Beach</strong>.
    </p>
  </div>
  <div class="fourth">
    <div class="figure"><%= image_tag "photos/contact2.jpg" %></div>
  </div>
</div>
<%= render 'book' %>

app/views/pages/index.html.erb
<div class="banner clearfix">
  <div class="figure">
    <%= image_tag "photos/intro_massage.jpg" %>
  </div>
  <div class="col">
  <div class="article pad-bot">
    <p>
      <strong class="title">Massage My Way</strong> was created to give people
access to on site and on demand massage therapy
of the very highest quality - affordably.
    </p>
    <p>
      Choose from a variety of
massage modalities to address your specific needs<br>
<%= link_to "View Our Services »", booking_path %>
    </p>

  </div>
  <div class="align-right">
    <%= link_to "Book Online Now", new_booking_path, :class => "button big", :rel =>"modal" %>
  <div class="pad-top"><em>or call</em> <span class="large">(310) 853-1830</span></div>
  </div>
  </div>
</div>
<div id="welcome">
  <h2>
  <span>Massage My Way</span> mobile massage services
  <br>
  The massage that comes to you
  </h2>
  <div class="under">
  </div>
  <div class="figure">
    <img src="/images/page1_img1.jpg" alt="">
  </div>
</div>

<div class="layout seven-five clearfix">
  <div class="col first">
    <div class="figure border">
      <span class="photo">
      <%= image_tag "photos/home1.jpg" %>
      <span class="overlay overlay-tall">
      </span>
    </div>
    <div class="entry">
      <h3>Quality Therapists</h3>
      <p>
        All our therapists are state licensed
professionals and many of them have
worked for the top spas in Los Angeles.
      </p>
    </div>
  </div>
  <div class="col second">
    <div class="figure border">
      <span class="photo">
      <%= image_tag "photos/home2.jpg" %>
      <span class="overlay overlay-tall">
      </span>
    </div>
    <div class="entry">
      <h3>Affordable</h3>
      <p>
        Click below to see some of our
sweet deals.
      </p>
      <%= link_to "View Pricing & Packages »", booking_path %>
    </div>
  </div>
</div>

app/views/pages/policies.html.erb
<h2>Our Policies</h2>
    <p>
      <strong>Individual Services</strong>
      <br>
      Same day cancellations are non-refundable. Advance reservations must be canceled 24 hours in advance or client will be charged in full.
    </p>
    <p>
      <strong>Event and Group Services</strong>
      <br>
      A non-refundable deposit is required to reserve your event date. The balance is due on the day of the event. 72 hours notice of cancellation is required so that no additional charges are incurred. The non-refundable deposit can be applied to another date/event held within three months of original event date.
    </p>
    <div class="figure border left">
      <span class="photo">
        <%= image_tag "photos/policies.jpg" %>
        <span class="overlay overlay-tall">
        </span>
    </div>
    <p>
      <strong>Payment Options</strong>
      <br>
      We accept Visa, MC, American Express, Discover, Debit cards and checks (we must receive the check two weeks prior to the event). Gratuities can be paid in cash or added to the credit card.
    </p>
    <p>
      <strong>Additional Charges for Long Distance Travel and After-Hours Bookings</strong>
      <br>
      There is a $25 surcharge for services requested before 9am or starting at 9pm and for travel
      outside our standard area.
    </p>
    <p>
      <strong>Waiting Fees</strong>
      <br>
      We give a 15 minute grace period then charge $25 for every 15 minutes the technician is kept waiting.
    </p>
    <p>
      <strong>Note:</strong>
      <br>
      Our spa technicians can refuse services if there are any contraindications, medical conditions that were not disclosed at time of reservation (example: broken skin or lesions) or if the client exhibits inappropriate conduct.
    </p>

<%= render 'book' %>

app/views/pages/services.html.erb
<div class="layout half clearfix">
  <div class="col first">

    <div class="figure border pad-bot">
      <span class="photo">
        <%= image_tag "photos/services1.jpg" %>
        <span class="overlay">
        </span>
    </div>
    <div class="entry pad-bot">
      <h4>Swedish Massage</h4>
      <p>
        consists of long gliding techniques with gentle kneading to your shoulders and large muscle groups. Swedish Massage improves your health, immune system and all organ systems for optimal wellness.
      </p>
    </div>
    <div class="entry pad-bot">
      <h4>Craniosacral Therapy</h4>
      <p>
        is a gentle approach that works to alleviate a range of sensory, motor or neurological disorders.  Your therapist listens to this system and assists the body in releasing restrictions which it had been unable to overcome on its own.
      </p>
    </div>
    <div class="entry pad-bot">
      <h4>Hot Stone Massage</h4>
      <p>
        is a variation on classic massage therapy. Heated smooth, flat stones are placed on key points on the body. The massage therapist may also hold the stones and use them to massage certain areas of the body. (Note: this is an add on treatment $15)
      </p>
    </div>
    <div class="entry pad-bot">
      <h4>Couples Massage</h4>
      <p>
        is a wonderful way to spend quality time with a friend, partner, lover or spouse. Each of you will receive a massage that is specifically catered to your needs. You will have your own therapist and will receive your sessions simultaneously on side by side massage tables.
      </p>
    </div>
    <div class="entry pad-bot">
      <h4>Dry Body Scrub</h4>
      <p>
        is a cleansing where your therapist will dry brush your body in circular movements, removing layers of dead skin. It will conclude with a 30, 60 or 90-minute massage depending on your preference. (Note: This is an add on treatment $10)
      </p>
    </div>
  </div>
  <div class="col second">

    <div class="entry pad-bot">
      <h4>Deep Tissue</h4>
      <p>
        focuses on realigning the deeper layers of muscle and fascia, also called connective tissue. the therapist works to release chronic muscle tension or knots.
      </p>
    </div>
    <div class="entry pad-bot">
      <h4>Shiatsu</h4>
      <p>
        is a traditional form of Asian bodywork designed to enhance and restore health. Through the application of pressure and stretching techniques shiatsu relieves muscle tension, eases joint stiffness and realigns the structure of the body.
      </p>
    </div>
    <div class="entry pad-bot">
      <h4>Thai Massage</h4>
      <p>
        is also called Thai yoga massage, because the therapist uses his or her hands, knees, legs, and feet to move you into a series of yoga-like stretches. People who try Thai massage sometimes say it is like doing yoga without any work, and say that it's both relaxing and energizing.
      </p>
    </div>
    <div class="entry pad-bot">
      <h4>Sports Massage</h4>
      <p>
        is a special form of massage and is typically used before, during, and after athletic events. The purpose of the massage is to prepare the athlete for peak performance, to drain away fatigue, to relieve swelling, to reduce muscle tension, to promote flexibility and to prevent injuries.
      </p>
    </div>
    <div class="entry">
      <h4>Reflexology</h4>
      <p>
        is based on the premise that each organ or part of the body is represented on the hands, feet & ears so that when your therapist applies pressure it stimulates the flow of energy, blood, nutrients, and nerve impulses to the corresponding organ or body part.
      </p>
    </div>
    <div class="figure border">
      <span class="photo">
        <%= image_tag "photos/services2.jpg" %>
        <span class="overlay">
        </span>
    </div>
  </div>
</div>
<%= render 'book' %>

app/views/pages/therapists.html.erb
<div class="wrapper pad_bot1">
  <h2>Our Therapists</h2>
  <figure class="left marg_right1">
    <img src="/images/page5_img1.jpg" alt="">
  </figure>
  <h4>Dov Gellis</h4>
  <p>
    blah blah blah
  </p>
</div>
<div class="wrapper">
  <figure class="left marg_right1">
    <img src="/images/page5_img2.jpg" alt="">
  </figure>
  <h4>Someone Else</h4>
  <p>
    blah blah.
  </p>
</div>